### ISSUE TITLE
Chrome Extension にスクリーンショット画像を貼り付ける

### ISSUE THREAD

**Issue by yasulab** [yasslab/event-description-template#1]
@hanachin ドアテンの流れを簡単に説明できそうなスクリーンショットを３枚ほど撮ってみたので、もし使えそうであれば [Chrome Extension の Dashboard](https://chrome.google.com/webstore/developer/dashboard/) からアップロードお願いします :bow: 
## 1st SS

![ss_1](https://cloud.githubusercontent.com/assets/155807/7764133/fd0c52ae-0086-11e5-9b75-9b80952f83e5.png)
## 2nd SS

![ss_2](https://cloud.githubusercontent.com/assets/155807/7764134/fd14e70c-0086-11e5-87d4-5ee40f118c33.png)
## 3rd SS

![ss_3](https://cloud.githubusercontent.com/assets/155807/7764135/fd197ba0-0086-11e5-90a4-01bf285acd55.png)

**Comment by hanachin** [comment]
スクリーンショットありがとうございます。アップロードしました。

**Comment by yasulab** [comment]
いえいえ〜 :smile: 一応 Doorkeeper の中の人にも伝えておきます :+1:

**Comment by yasulab** [comment]
Doorkeeperの中の人にも伝えておきました :mega: 

https://www.facebook.com/groups/1541181422773074/permalink/1819889574902256/
