### ISSUE TITLE
optionページでCSSが読み込めない

### ISSUE THREAD

**Issue by yasulab** [yasslab/event-description-template#3]
updateした場合にのみ発生する現象なのかもしれないですが、CSSが適用されなくなってしまいました :sob: 

![screen shot 2015-05-23 at 15 09 04](https://cloud.githubusercontent.com/assets/155807/7782682/ce6ddfb2-015d-11e5-8528-35ebd0c5158c.png)

**Comment by yasulab** [comment]
`styles/vendor.css` が見つからないみたいなので、ここら辺が原因かも

https://github.com/yasslab/event-description-template/blob/master/app/options.html#L6-L10

**Comment by hanachin** [comment]
うまくビルドできてなかったようなので再度ビルドしてアップロードしました。

**Comment by yasulab** [comment]
fixed! ありがと〜〜 :star2: 

![screen shot 2015-05-23 at 16 36 45](https://cloud.githubusercontent.com/assets/155807/7782949/f224af1a-0169-11e5-9bb8-7bf1e7587624.png)
